version: '3.8'
services:
  learnzone-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
  learnzone-backend:
    image: learnzone-backend2
    ports:
      - '8000:8000'